source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'KoalaDemo' do
  pod 'Koala-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/koala/v2.0-ios-update/binding/ios/Koala-iOS.podspec'
  pod 'ios-voice-processor', '~> 1.1.0'
end
