name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  input_path:
    required: true
  output_path:
    required: true

runs:
  using: "composite"
  steps:
  - name: demo
    run: >
      ./build/koala_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -i ${{ inputs.input_path }}
        -o ${{ inputs.output_path }}
    working-directory: demo/c
    shell: bash
