name: C

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'example/**'
      - 'src/**'
      - 'node/**'
      - 'CMakeLists.txt'
      - '.github/workflows/c.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'example/**'
      - 'src/**'
      - 'node/**'
      - 'CMakeLists.txt'
      - '.github/workflows/c.yml'

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build
      run: cmake --build ./build

    - name: Run get audio devices
      run: ./demo --show_audio_devices
      working-directory: build

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build
      run: cmake --build ./build

    - name: Run get audio devices
      run: ./demo --show_audio_devices
      working-directory: build
