name: iOS BrowserStack Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'binding/ios/KoalaAppTest/**'
      - 'resources/audio_samples/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'binding/ios/KoalaAppTest/**'
      - 'resources/audio_samples/**'

defaults:
  run:
    working-directory: binding/ios/KoalaAppTest

jobs:
  build:
    name: Run iOS Tests on BrowserStack
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          pip3 install requests

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Inject AppID
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          KoalaAppTestUITests/KoalaAppTestUITests.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -workspace KoalaAppTest.xcworkspace
          -sdk iphoneos
          -scheme KoalaAppTest
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Generating ipa
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          mkdir Payload &&
          cp -r KoalaAppTest.app Payload &&
          zip --symlinks -r KoalaAppTest.ipa Payload &&
          rm -r Payload

      - name: Zipping Tests
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          zip --symlinks -r KoalaAppTestUITests.zip KoalaAppTestUITests-Runner.app

      - name: Run tests on BrowserStack
        run: python3 ../../../script/automation/browserstack.py
          --type xcuitest
          --username "${{secrets.BROWSERSTACK_USERNAME}}"
          --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
          --project_name "Koala-iOS"
          --devices "ios-min-max"
          --app_path "ddp/Build/Products/Debug-iphoneos/KoalaAppTest.ipa"
          --test_path "ddp/Build/Products/Debug-iphoneos/KoalaAppTestUITests.zip"
