name: iOS AppCenter Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-appcenter.yml'
      - 'binding/ios/KoalaAppTest/KoalaAppTestUITests/KoalaAppTestUITests.swift'
      - 'binding/ios/KoalaAppTest/Podfile.lock'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-appcenter.yml'
      - 'binding/ios/KoalaAppTest/KoalaAppTestUITests/KoalaAppTestUITests.swift'
      - 'binding/ios/KoalaAppTest/Podfile.lock'

defaults:
  run:
    working-directory: binding/ios/KoalaAppTest

jobs:
  build:
    name: Run iOS Tests on AppCenter
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Inject AppID
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          KoalaAppTestUITests/KoalaAppTestUITests.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -workspace KoalaAppTest.xcworkspace
          -sdk iphoneos
          -scheme KoalaAppTest
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Run Tests on AppCenter
        run: appcenter test run xcuitest
          --token ${{secrets.APPCENTERAPITOKEN}}
          --app "Picovoice/Koala-iOS"
          --devices "Picovoice/ios-min-max"
          --test-series "koala-ios"
          --locale "en_US"
          --build-dir ddp/Build/Products/Debug-iphoneos
