name: SpellCheck

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install CSpell
        run: npm install -g cspell

      - name: Run CSpell
        run: cspell --config resources/.lint/spell-check/.cspell.json "**/*"
